### ISSUE TITLE
java.net.UnknownServiceException: CLEARTEXT communication to gank.io not permitted by network security policy

### ISSUE THREAD

**Issue by javamagong** [V1sk/VettelGank#1]
高版本联网失败。
解决方式[参考链接]：
* `http`请求改为`https`;
* 降低目标版本到27以下；
* 更改安全配置。-（建议）

[参考链接]:https://medium.com/@bouffard.jul/build-an-android-app-using-a-non-secure-api-in-android-9-88c9bafbc12

**Comment by V1sk** [comment]
已解决，感谢反馈！
