### ISSUE TITLE
项目打不开..

### ISSUE THREAD

**Issue by wongyue** [V1sk/VettelGank#2]
Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve org.jetbrains.anko:anko-sqlite:0.10.8.
Open File
Show Details

疯狂出这个，网上说的招式都搞了一遍，不得行。。。
kotlin项目头回遇到这个问题...

**Comment by V1sk** [comment]
试试删掉 app/build.gradle 里面的
`implementation "org.jetbrains.anko:anko-sqlite:$anko_version"`
事实上项目没有用 anko的 sqlite，回头我更新一下

**Comment by wongyue** [comment]
不止 这一个，老哥 "org.jetbrains.anko:anko-xxxxx 有十多个这种，
